version: '3'

services:
  fastapi:
    build: fastapi/
    ports: 
      - 8000:8000
    networks:
      - deploy_network
    container_name: fastapi
    volumes:
      - "./fastapi:/app/"

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - deploy_network
    container_name: streamlit
    volumes:
      - "./streamlit:/app"

  nginx:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx_conf.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - fastapi
      - streamlit

networks:
  deploy_network:
    driver: bridge