version: '3'

services:
  fastapi:
    build: 
      context: fastapi
      dockerfile: Dockerfile
    restart: unless-stopped
    ports: 
      - 8008:8008
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 8000
    networks:
      - frontend
      - backend
    container_name: fastapi-docker
    volumes:
      - "./fastapi:/app/"

  streamlit:
    build: streamlit/
    depends_on:
      - fastapi
    ports: 
        - 8501:8501
    networks:
      - frontend
    container_name: streamlit-docker
    volumes:
      - "./streamlit:/app"

  webserver:
    build:
      context: nginx
      dockerfile: Dockerfile
    image: digitalocean.com/webserver:latest
    container_name: webserver
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_NAME: "webserver"
      APP_DEBUG: "true"
      SERVICE_NAME: "webserver"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - nginxdata:/var/log/nginx
    depends_on:
      - fastapi
      - streamlit
    networks:
      - frontend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge